name: Push Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - *

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [self-hosted, Linux]

    steps:
      - run: echo "foo content" > foo.txt
      - uses: actions/upload-artifact@v2
        with:
          name: foo-artifact
          path: foo.txt
      - uses: actions/checkout@v2
        with:
          clean: false
      - uses: actions/github-script@v5
        with:
          script: |
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])
            core.exportVariable("GITHUB_RETENTION_DAYS", process.env["GITHUB_RETENTION_DAYS"])
      - run: cargo run --example artifact
