name: Manual command run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      command:
        description: "Command to be run."
        required: true
        type: string
        default: "cargo run --example artifact"
      target:
        description: "What runner should be used."
        required: true
        type: choice
        options:
          - '["self-hosted", "Linux"]'
          - '["ubuntu-latest"]'
          - '["self-hosted", "Windows"]'
          - '["windows-latest"]'
          - '["self-hosted", "macOS"]'
          - '["macos-latest"]'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ fromJSON(github.event.inputs.target) }}

    steps:
      - run: echo "foo content" > foo.txt
      - uses: actions/upload-artifact@v2
        with:
          name: foo-artifact
          path: foo.txt
      - uses: actions/checkout@v2
        with:
          clean: false
      - uses: actions/github-script@v5
        with:
          script: |
            core.setEnvironmentVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.setEnvironmentVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])
            core.setEnvironmentVariable("GITHUB_RETENTION_DAYS", process.env["GITHUB_RETENTION_DAYS"])
      - run: ${{ github.event.inputs.command }}
