name: Manual command run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      command:
        description: "Command to be run."
        required: true
        type: string
        default: "cargo run --example artifact"
      target:
        description: "What runner should be used."
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - "[self-hosted, Windows]"
          - "[self-hosted, Linux]"
          - "[self-hosted, macOS]"


          # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ github.event.inputs.target }}

    steps:
      - run: echo "foo content" > foo.txt
      - uses: actions/upload-artifact@v2
        with:
          name: foo-artifact
          path: foo.txt
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            set_env("ACTIONS_RUNTIME_TOKEN", os.environ["ACTIONS_RUNTIME_TOKEN"])
            set_env("ACTIONS_RUNTIME_URL", os.environ["ACTIONS_RUNTIME_URL"])
            set_env("GITHUB_RETENTION_DAYS", os.environ["GITHUB_RETENTION_DAYS"])
      - run: ${{ github.event.inputs.command }}
