name: Experimental command

# Controls when the workflow will run
on:
  workflow_dispatch:

  push:
    branches:
      - "*"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [ubuntu-latest]
          - [windows-latest]
          - [macos-latest]
          - [self-hosted, Windows, engine]
          - [self-hosted, Linux, engine]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])
            core.exportVariable("GITHUB_RETENTION_DAYS", process.env["GITHUB_RETENTION_DAYS"])

      - uses: actions/checkout@v2
        with:
          ref: wip/mwu/new-ide-build
          repository: enso-org/enso
          path: enso

      - uses: actions/checkout@v2
        with:
          path: ci-build
          clean: false

      - name: Run a multi-line script
        run: cargo run --example build-gui -- ../enso build
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}
