name: Experimental command

# Controls when the workflow will run
on:
  workflow_dispatch:

  push:

env:
  ENSO_BUILD_REPO_PATH: enso
  ENSO_BUILD_REPO_REMOTE: enso-org/ci-build
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: full

jobs:
  prepare:
    runs-on: [mwu-deluxe]
    outputs:
      ENSO_VERSION: ${{ steps.prepare-step.outputs.ENSO_VERSION }}
      ENSO_RELEASE_ID: ${{ steps.prepare-step.outputs.ENSO_RELEASE_ID }}
    steps:
      - uses: enso-org/ci-build/actions/install@wip/mwu/engine
      - run: enso-build-cli --help
      - run: enso-build-cli release --kind nightly create-draft
        id: prepare-step

  build:
    needs: prepare
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [mwu-deluxe]
      fail-fast: false
    steps:
      - uses: enso-org/ci-build/actions/install@wip/mwu/engine
      - run: enso-build-engine --kind nightly upload-asset

  finish:
    runs-on: [mwu-deluxe]
    needs: [prepare, build]
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    steps:
      - uses: enso-org/ci-build/actions/install@wip/mwu/engine
      - run: enso-build-cli release --kind nightly publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTEFACT_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTEFACT_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
