name: Experimental command

# Controls when the workflow will run
on:
  workflow_dispatch:

  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [macos-latest]
          - [self-hosted, Windows, engine]
          - [self-hosted, Linux, engine]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: enso-org/ci-build/actions/install@wip/mwu/new-ide-build
        with:
          enso_ref: ${{ github.ref }}
      - name: Run a multi-line script
        run: enso-build2 ide build
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RUST_LOG: info,ide_ci=trace,enso_build2=trace
#
#      - name: Upload Content Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: content
#          path: dist/content
#        if: runner.os == 'Linux'
#      - name: Upload Artifacts (macOS, dmg)
#        uses: actions/upload-artifact@v1
#        with:
#          name: enso-mac-${{ env.ENSO_VERSION }}.dmg
#          path: >-
#            enso/dist/client/enso-mac-${{ env.ENSO_VERSION }}.dmg
#        if: runner.os == 'macOS'
#      - name: Upload Artifacts (macOS, dmg.sha256)
#        uses: actions/upload-artifact@v1
#        with:
#          name: >-
#            enso-mac-${{ env.ENSO_VERSION }}.dmg.sha256
#          path: >-
#            enso/dist/client/enso-mac-${{ env.ENSO_VERSION }}.dmg.sha256
#        if: runner.os == 'macOS'
#      - name: Upload Artifacts (Windows, exe)
#        uses: actions/upload-artifact@v1
#        with:
#          name: enso-win-${{ env.ENSO_VERSION }}.exe
#          path: >-
#            enso/dist/client/enso-win-${{ env.ENSO_VERSION }}.exe
#        if: runner.os == 'Windows'
#      - name: Upload Artifacts (Windows, exe.sha256)
#        uses: actions/upload-artifact@v1
#        with:
#          name: >-
#            enso-win-${{ env.ENSO_VERSION }}.exe.sha256
#          path: >-
#            enso/dist/client/enso-win-${{ env.ENSO_VERSION }}.exe.sha256
#        if: runner.os == 'Windows'
#      - name: Upload Artifacts (Linux, AppImage)
#        uses: actions/upload-artifact@v1
#        with:
#          name: >-
#            enso-linux-${{ env.ENSO_VERSION }}.AppImage
#          path: >-
#            enso/dist/client/enso-linux-${{ env.ENSO_VERSION }}.AppImage
#        if: runner.os == 'Linux'
#      - name: Upload Artifacts (Linux, AppImage.sha256)
#        uses: actions/upload-artifact@v1
#        with:
#          name: >-
#            enso-linux-${{ env.ENSO_VERSION }}.AppImage.sha256
#          path: >-
#            enso/dist/client/enso-linux-${{ env.ENSO_VERSION }}.AppImage.sha256
#        if: runner.os == 'Linux'
