name: Experimental command

# Controls when the workflow will run
on:
  workflow_dispatch:

  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [mwu-deluxe]
        command:
          - "engine"
          - "project-manager"
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: enso-org/ci-build/actions/install@wip/mwu/engine
#        with:
#          enso_ref: ${{ github.ref }}
      - name: Run a multi-line script
        run: enso-build2 --repo-remote enso-org/ci-build ${{ matrix.command }}
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RUST_BACKTRACE: full
