name: Build Engine

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: [self-hosted]
    outputs:
      ENSO_VERSION: ${{ steps.prepare-step.outputs.ENSO_VERSION }}
      ENSO_RELEASE_ID: ${{ steps.prepare-step.outputs.ENSO_RELEASE_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: enso-org/enso
          path: enso
          ref: wip/mwu/engine-version-from-env
      - uses: actions/checkout@v2
        with:
          path: ci-build
          clean: false
      - name: Run a multi-line script
        id: prepare-step
        run: cargo run --bin enso-build -- ../enso prepare --kind nightly
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}

  finish:
    runs-on: [self-hosted]
    needs: [prepare, build]
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: enso-org/enso
          path: enso
          ref: wip/mwu/engine-version-from-env
      - uses: actions/checkout@v2
        with:
          path: ci-build
          clean: false
      - name: Run a multi-line script
        id: prepare-step
        run: cargo run --bin enso-build -- ../enso finish --kind nightly
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    needs: prepare
    env:
      ENSO_VERSION: ${{needs.prepare.outputs.ENSO_VERSION}}
      ENSO_RELEASE_ID: ${{needs.prepare.outputs.ENSO_RELEASE_ID}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - [macos-latest]
          - [self-hosted, Windows, engine]
          - [self-hosted, Linux, engine]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          repository: enso-org/enso
          path: enso
          ref: wip/mwu/engine-version-from-env
      - uses: actions/checkout@v2
        with:
          path: ci-build
          clean: false

      - name: Setup conda
        uses: s-weigand/setup-conda@v1.0.5
        if: contains(matrix.os, 'self-hosted') == false
        with:
          update-conda: false
          conda-channels: anaconda, conda-forge

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: cargo run --bin enso-build -- ../enso upload --kind nightly
        working-directory: ${{ github.workspace }}/ci-build
        env:
          GITHUB_TOKEN: ${{ github.token }}
